input {
  beats {
    port => 5044
  }
}

filter {

  if [log_type] == "vpn" {

    grok {
      match => {
        "message" => "%{TIMESTAMP_ISO8601:log_timestamp} %{HOSTNAME:gateway} %{WORD:action} user=%{USERNAME:user} src_ip=%{IP:src_ip} country=%{WORD:country}"
      }
    }

  }

}

output {

  stdout {
    codec => rubydebug
  }

  opensearch {

    hosts => ["https://opensearch:9200"]

    user => "admin"
    password => "SOCExam!1234"

    ssl_certificate_verification => false

    index => "%{log_type}-%{+YYYY.MM.dd}"

  }

}